from __future__ import annotations

import importlib
import logging
import os
import sys
import threading
import time
from collections import OrderedDict
from pathlib import Path
from typing import Any

from PIL import Image

from app.config import Settings
from app.constants import wardrobe as wardrobe_constants
from app.runtime.wardrobe_types import WardrobeRunResult, WardrobeRuntimeStatus

logger = logging.getLogger("glamify-ai")


class WardrobeRuntimeError(RuntimeError):
    pass


class WardrobeGenerationError(RuntimeError):
    pass


WARDROBE_CATEGORIES: tuple[str, ...] = ("top", "bottom", "dress")


class QwenWardrobeAitkClient:
    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._aitk_root = Path(settings.ai_toolkit_root).expanduser()
        self._model_path = Path(settings.qwen_image_edit_model_path).expanduser()
        self._specialist_paths: dict[str, Path] = {
            "top": Path(settings.wardrobe_lora_top_path).expanduser(),
            "bottom": Path(settings.wardrobe_lora_bottom_path).expanduser(),
            "dress": Path(settings.wardrobe_lora_dress_path).expanduser(),
        }
        self._pipeline: Any | None = None
        self._network: Any | None = None
        self._toolkit: dict[str, Any] | None = None
        self._torch_module: Any | None = None
        self._specialist_state_dicts: dict[str, OrderedDict[str, Any]] = {}
        self._active_specialist: str | None = None
        self._load_lock = threading.Lock()
        self._infer_lock = threading.Lock()
        self._device = "cpu"
        self._dtype_name = "float32"

    def warmup(self) -> None:
        self._ensure_ready()
        self._load_specialist_state_dicts()

    def status(self) -> WardrobeRuntimeStatus:
        return WardrobeRuntimeStatus(
            loaded=self._pipeline is not None and self._network is not None,
            backend="ai_toolkit_exact" if self._pipeline is not None else None,
            loras_loaded=bool(self._specialist_state_dicts),
        )

    def set_active_specialist(self, category: str) -> None:
        if category not in WARDROBE_CATEGORIES:
            raise WardrobeRuntimeError(f"Unknown wardrobe specialist category: {category}")
        self._ensure_ready()
        self._load_specialist_state_dicts()
        if self._active_specialist == category:
            return
        if self._network is None:
            raise WardrobeRuntimeError("AI-Toolkit wardrobe LoRA network is not initialized.")
        self._network.load_state_dict(self._specialist_state_dicts[category], strict=False)
        self._network._update_torch_multiplier()
        self._active_specialist = category
        logger.info("Switched wardrobe extraction LoRA to '%s'", category)

    def run_extract(
        self,
        *,
        input_image_path: str,
        prompt: str,
        garment_type: str,
        output_path: str,
    ) -> WardrobeRunResult:
        self._ensure_ready()
        if (
            self._pipeline is None
            or self._network is None
            or self._toolkit is None
            or self._torch_module is None
        ):
            raise WardrobeRuntimeError("AI-Toolkit wardrobe runtime is not loaded.")

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        started_at = time.perf_counter()
        conf = self._toolkit["GenerateImageConfig"](
            prompt=str(prompt).strip(),
            width=wardrobe_constants.OUTPUT_WIDTH,
            height=wardrobe_constants.OUTPUT_HEIGHT,
            negative_prompt="",
            seed=wardrobe_constants.GENERATION_SEED,
            guidance_scale=wardrobe_constants.GENERATION_GUIDANCE_SCALE,
            guidance_rescale=wardrobe_constants.GENERATION_GUIDANCE_RESCALE,
            num_inference_steps=wardrobe_constants.GENERATION_STEPS,
            network_multiplier=wardrobe_constants.GENERATION_NETWORK_MULTIPLIER,
            output_path=str(output_file),
            output_ext="jpg",
            ctrl_img_1=str(input_image_path),
            do_cfg_norm=wardrobe_constants.GENERATION_DO_CFG_NORM,
        )

        with self._infer_lock, self._torch_module.inference_mode():
            self.set_active_specialist(garment_type)
            self._pipeline.generate_images(
                [conf],
                sampler=wardrobe_constants.GENERATION_SAMPLER,
            )

        if not output_file.exists():
            raise WardrobeGenerationError("No image was generated by the wardrobe runtime.")

        image = Image.open(output_file).convert("RGB")
        metadata = {
            "backend": "ai_toolkit_exact",
            "architecture": "qwen_image_edit_plus",
            "model_source": str(self._model_path),
            "ai_toolkit_root": str(self._aitk_root),
            "checkpoint_path": str(self._specialist_paths[garment_type]),
            "lora_key": garment_type,
            "lora_rank": wardrobe_constants.LORA_RANK,
            "lora_alpha": wardrobe_constants.LORA_ALPHA,
            "network_multiplier": wardrobe_constants.GENERATION_NETWORK_MULTIPLIER,
            "guidance_scale": wardrobe_constants.GENERATION_GUIDANCE_SCALE,
            "guidance_rescale": wardrobe_constants.GENERATION_GUIDANCE_RESCALE,
            "do_cfg_norm": wardrobe_constants.GENERATION_DO_CFG_NORM,
            "sampler": wardrobe_constants.GENERATION_SAMPLER,
            "seed": wardrobe_constants.GENERATION_SEED,
            "steps": wardrobe_constants.GENERATION_STEPS,
            "control_order": {"ctrl_img_1": "garment_input"},
            "output_size": {
                "width": wardrobe_constants.OUTPUT_WIDTH,
                "height": wardrobe_constants.OUTPUT_HEIGHT,
            },
            "dtype": self._dtype_name,
            "device": self._device,
        }
        return WardrobeRunResult(
            image=image,
            metadata=metadata,
            wall_seconds=float(round(time.perf_counter() - started_at, 3)),
        )

    def _ensure_ready(self) -> None:
        if self._pipeline is not None and self._network is not None and self._toolkit is not None:
            return
        with self._load_lock:
            if self._pipeline is None or self._network is None or self._toolkit is None:
                self._load_runtime()

    def _load_runtime(self) -> None:
        if not self._aitk_root.exists():
            raise WardrobeRuntimeError(f"AI-Toolkit root does not exist: {self._aitk_root}")
        if not self._model_path.exists():
            raise WardrobeRuntimeError(f"Qwen model path does not exist: {self._model_path}")

        os.environ.setdefault("DISABLE_TELEMETRY", "YES")
        os.environ.setdefault("NO_ALBUMENTATIONS_UPDATE", "1")
        # AI-Toolkit resolves some assets relative to its repository root.
        # This is process-global, so the bootstrap keeps this API to one worker.
        os.chdir(self._aitk_root)
        aitk_root_str = str(self._aitk_root)
        if aitk_root_str not in sys.path:
            sys.path.insert(0, aitk_root_str)

        try:
            config_module = importlib.import_module("toolkit.config_modules")
            lora_module = importlib.import_module("toolkit.lora_special")
            train_tools_module = importlib.import_module("toolkit.train_tools")
            model_module = importlib.import_module("toolkit.util.get_model")
        except Exception as exc:
            raise WardrobeRuntimeError(
                f"Unable to import AI-Toolkit modules from {self._aitk_root}: {exc}",
            ) from exc

        ModelConfig = config_module.ModelConfig
        NetworkConfig = config_module.NetworkConfig
        GenerateImageConfig = config_module.GenerateImageConfig
        LoRASpecialNetwork = lora_module.LoRASpecialNetwork
        get_torch_dtype = train_tools_module.get_torch_dtype
        get_model_class = model_module.get_model_class

        model_config = ModelConfig(
            **{
                "name_or_path": str(self._model_path),
                "arch": "qwen_image_edit_plus",
                "quantize": False,
                "quantize_te": False,
                "low_vram": False,
            },
        )
        net_config = NetworkConfig(
            **{
                "type": "lora",
                "linear": wardrobe_constants.LORA_RANK,
                "linear_alpha": wardrobe_constants.LORA_ALPHA,
            },
        )
        torch_module = importlib.import_module("torch")
        self._torch_module = torch_module
        self._device = "cuda:0" if torch_module.cuda.is_available() else "cpu"
        self._dtype_name = "bfloat16" if self._device.startswith("cuda") else "float32"

        ModelClass = get_model_class(model_config)
        sampler = ModelClass.get_train_scheduler()
        dtype = get_torch_dtype("bf16" if self._device.startswith("cuda") else "fp32")

        sd = ModelClass(
            device=self._device,
            model_config=model_config,
            dtype=dtype,
            noise_scheduler=sampler,
        )
        sd.load_model()
        if hasattr(sd, "pipeline") and self._device.startswith("cuda"):
            sd.pipeline.to(self._device, dtype)

        network_kwargs = dict(getattr(net_config, "network_kwargs", {}) or {})
        if hasattr(sd, "target_lora_modules"):
            network_kwargs["target_lin_modules"] = sd.target_lora_modules

        network = LoRASpecialNetwork(
            text_encoder=sd.text_encoder,
            unet=sd.get_model_to_train(),
            lora_dim=net_config.linear,
            multiplier=wardrobe_constants.GENERATION_NETWORK_MULTIPLIER,
            alpha=net_config.linear_alpha,
            train_unet=True,
            train_text_encoder=False,
            conv_lora_dim=net_config.conv,
            conv_alpha=net_config.conv_alpha,
            is_sdxl=model_config.is_xl or model_config.is_ssd,
            is_v2=model_config.is_v2,
            is_v3=model_config.is_v3,
            is_pixart=model_config.is_pixart,
            is_auraflow=model_config.is_auraflow,
            is_flux=model_config.is_flux,
            is_lumina2=model_config.is_lumina2,
            is_ssd=model_config.is_ssd,
            is_vega=model_config.is_vega,
            dropout=net_config.dropout,
            use_text_encoder_1=model_config.use_text_encoder_1,
            use_text_encoder_2=model_config.use_text_encoder_2,
            network_config=net_config,
            network_type=net_config.type,
            transformer_only=net_config.transformer_only,
            is_transformer=sd.is_transformer,
            base_model=sd,
            **network_kwargs,
        )
        network.force_to(sd.device_torch, dtype=torch_module.float32)
        sd.network = network
        network._update_torch_multiplier()
        network.apply_to(sd.text_encoder, sd.get_model_to_train(), False, True)

        self._pipeline = sd
        self._network = network
        self._toolkit = {"GenerateImageConfig": GenerateImageConfig}
        logger.info("Qwen wardrobe AI-Toolkit runtime ready (device=%s)", self._device)

    def _load_specialist_state_dicts(self) -> None:
        if self._network is None:
            raise WardrobeRuntimeError("AI-Toolkit wardrobe LoRA network is not initialized.")
        if self._specialist_state_dicts:
            return
        for category in WARDROBE_CATEGORIES:
            path = self._specialist_paths[category]
            if not path.exists():
                raise WardrobeRuntimeError(
                    f"Wardrobe specialist checkpoint missing for '{category}': {path}",
                )
            self._network.load_weights(str(path))
            snapshot = OrderedDict(
                (key, tensor.detach().clone())
                for key, tensor in self._network.state_dict().items()
            )
            self._specialist_state_dicts[category] = snapshot
            logger.info("Cached wardrobe LoRA weights: %s -> %s", category, path)
        first = WARDROBE_CATEGORIES[0]
        self._network.load_state_dict(self._specialist_state_dicts[first], strict=False)
        self._network._update_torch_multiplier()
        self._active_specialist = first
