from app.constants import wardrobe as wardrobe_constants


def test_wardrobe_marqo_candidates_include_analyze_lane_parent_category_keys() -> None:
    expected_by_parent = {
        "tops": {
            "blouses",
            "bodysuits",
            "bustiers",
            "corsets",
            "crop_tops",
            "hoodies",
            "knitwear",
            "long_sleeve_t_shirts",
            "polo_shirts",
            "shirts",
            "sleeveless_tops",
            "sweater_vests",
            "sweaters",
            "sweatshirts",
            "t_shirts",
            "tank_tops_and_camis",
            "tunics",
        },
        "outerwear": {
            "biker_jackets",
            "blazers",
            "bomber_jackets",
            "capes",
            "cardigans",
            "coats",
            "denim_jackets",
            "down_jackets",
            "jackets",
            "leather_jackets",
            "parkas",
            "ponchos",
            "puffer_jackets",
            "trench_coats",
            "varsity_jackets",
            "windbreakers",
        },
        "layering_pieces": {
            "boleros",
            "shawls",
            "shrugs",
            "vests",
        },
        "office_wear_formal": {
            "knit_tops",
            "structured_dresses",
            "suits",
            "work_dresses",
        },
        "bottoms": {
            "cargo_pants",
            "dress_pants",
            "jeggings",
            "jeans",
            "leggings",
            "palazzos",
            "pants",
            "shorts",
            "skorts",
            "sweatpants",
            "track_pants",
            "trousers",
            "wide_leg_pants",
        },
        "skirts": {
            "a_line_skirts",
            "denim_skirts",
            "maxi_skirts",
            "midi_skirts",
            "mini_skirts",
            "pencil_skirts",
            "pleated_skirts",
            "wrap_skirts",
        },
        "activewear_sportswear": {
            "bike_shorts",
            "gym_leggings",
            "sports_jackets",
            "sports_tops",
            "tennis_skirts",
            "tracksuits",
        },
        "dresses": {
            "bodycon_dresses",
            "casual_dresses",
            "day_dresses",
            "evening_dresses",
            "jacket_dresses",
            "maxi_dresses",
            "midi_dresses",
            "mini_dresses",
            "off_shoulder_dresses",
            "party_dresses",
            "shirt_dresses",
            "slip_dresses",
            "strapless_dresses",
            "sweater_dresses",
            "t_shirt_dresses",
            "wrap_dresses",
        },
        "loungewear": {
            "lounge_pants",
            "lounge_sets",
            "lounge_tops",
            "oversized_hoodies",
            "soft_knit_sets",
        },
        "sets_one_pieces": {
            "co_ords",
            "jumpsuits",
            "matching_sets",
            "playsuits",
            "rompers",
            "two_piece_sets",
        },
    }

    actual_by_parent: dict[str, set[str]] = {}
    for candidates in wardrobe_constants.MARQO_CANDIDATES_BY_TYPE.values():
        for candidate in candidates:
            actual_by_parent.setdefault(candidate.parent_key, set()).add(candidate.key)

    for parent_key, expected_keys in expected_by_parent.items():
        assert expected_keys <= actual_by_parent[parent_key]
