from fastapi import status as http_status

OK = http_status.HTTP_200_OK
BAD_REQUEST = http_status.HTTP_400_BAD_REQUEST
UNAUTHORIZED = http_status.HTTP_401_UNAUTHORIZED
FORBIDDEN = http_status.HTTP_403_FORBIDDEN
NOT_FOUND = http_status.HTTP_404_NOT_FOUND
CONFLICT = http_status.HTTP_409_CONFLICT
TOO_MANY_REQUESTS = http_status.HTTP_429_TOO_MANY_REQUESTS
UNPROCESSABLE_CONTENT = http_status.HTTP_422_UNPROCESSABLE_CONTENT
SERVICE_UNAVAILABLE = http_status.HTTP_503_SERVICE_UNAVAILABLE
GATEWAY_TIMEOUT = http_status.HTTP_504_GATEWAY_TIMEOUT
INTERNAL_SERVER_ERROR = http_status.HTTP_500_INTERNAL_SERVER_ERROR
