from __future__ import annotations

ALLOWED_IMAGE_FORMATS = {"JPEG", "PNG", "WEBP"}
ALLOWED_IMAGE_MIME_TYPES = {"image/jpeg", "image/png", "image/webp"}

NORMALIZED_LONG_EDGE_PX = 1248
MIN_NORMALIZED_EDGE_PX = 512
JPEG_QUALITY = 95
AZURE_UPLOAD_TIMEOUT_SECONDS = 60
STORAGE_PREFIX = "inputs"

PERSON_DETECTION_MODEL_ID = "PekingU/rtdetr_r50vd_coco_o365"

PERSON_DETECTION_SCORE_THRESHOLD = 0.10
PRIMARY_PERSON_SCORE_THRESHOLD = 0.50
PRIMARY_PERSON_MIN_HEIGHT_RATIO = 0.35
PRIMARY_PERSON_MIN_AREA_RATIO = 0.12
PRIMARY_PERSON_MIN_BOTTOM_RATIO = 0.40
BLUR_SCORE_THRESHOLD = 45.0

SECONDARY_LARGE_PERSON_SCORE_THRESHOLD = 0.70
SECONDARY_LARGE_PERSON_AREA_RATIO = 0.20
